### PR TITLE
Add support for aptly-api service on systemd systems

### PR DESCRIPTION
**Pull request by zipkid**

### CODE REVIEW

**Comment by jhooyberghs** [comment]
Anything incomplete on this PR to get it merged? We started using the fork with these commits since we need systemd support.

**Comment by rgevaert** [comment]
Same here.  I'm also now on the fork.

**Comment by zipkid** [comment]
Hi.
Something seems to be wrong with the tests on Travis....
The spec tests run clean on my system.

**Comment by deanwilson** [comment]
Thank you for submitting this fix, and apologies for the delay in getting time allocated to review it.

**Comment by deanwilson** [comment]
This has also been pushed to the PuppetForge.

**Pull request merged**
