### PR TITLE
Support for puppetlabs-apt > 2.0 fixes #34

### LINKED ISSUE #34: Support for puppetlabs-apt > 2.0
Currently, this module requires apt < 2.0

It would be nice to support newer versions of the module, I believe the only problem I could spot was the include_src in:
https://github.com/gds-operations/puppet-aptly/blob/master/manifests/init.pp#L68

### PR DESCRIPTION
**Pull request by zxjinn**
After reading the feedback from @mattbostock in #34 this appears to be what is wanted, if it's not let me know and I will modify the PR.

### CODE REVIEW

**Comment by ITler** [comment]
+1 for PR merge

**Comment by mattbostock** [comment]
Thanks for raising this @zxjinn! There's an unrelated build failure we need to fix before reviewing your PR; we'll get to this as soon as we can.

**Comment by jacobbednarz** [comment]
@zxjinn it looks like master has been resolved and shouldn't be throwing that style error. would you be able to trigger another build to get this green?

**Comment by zxjinn** [comment]
Awesome @jacobbednarz! after a master merge and a quick lint fix we're good to go. :mag:

**Comment by jacobbednarz** [comment]
awesome stuff! looking forward to getting this in master :tada:

**Comment by alexmuller** [comment]
Merged in #46, thanks for making this change @zxjinn.

**Comment by zxjinn** [comment]
Thank you!

**Comment by ITler** [comment]
Thanks!!

**Pull request closed without merging**
